### ISSUE TITLE
Disable github-actions closing valid Issues and PRs

### ISSUE THREAD

**Issue by Jarodiv** [terraform-aws-modules/terraform-aws-transit-gateway#110]
In this project valid issues and PRs are getting closed due to inactivity from the maintainers.

I understand the idea of closing issues if they are inactive but closing them automatically doesn't make sense if it is the maintainers who fail to respond in time. I see many issues/PRs closed while still waiting for a review.

With this setup, adding features or fixing bugs basically requires contributors to redo the work over and over again, until it finally gets some attention.

## Describe the solution you'd like.
Either ensure that maintainers take are of contributions (issues or code) within the auto-stale period or disable the auto closing.

## Describe alternatives you've considered.
Posting "keep alive" comments work, until you date to go to vacations or simply are busy. Also this "workaround" totally messes up with the purpose of the comments system.

**Comment by Jarodiv** [comment]
"Keep alive" post

**Comment by Jarodiv** [comment]
"Keep alive" post

**Comment by Jarodiv** [comment]
"Keep alive" post

**Comment by Jarodiv** [comment]
"Keep alive" post

**Comment by Jarodiv** [comment]
"Keep alive" post

**Comment by Jarodiv** [comment]
"Keep alive" post

**Comment by bryantbiggs** [comment]
Thank you but we do not have plans to remove the integrations at this time
