### ISSUE TITLE
Requesting supporting diagrams and documentation

### ISSUE THREAD

**Issue by stv-io** [terraform-aws-modules/terraform-aws-transit-gateway#124]
## Is your request related to a problem? Please describe.

This module is pretty awesome and provides valid, powerful and useful features, however it lacks a core part of documentation, which is a network and topology diagram.

## Describe the solution you'd like.
For the proposed code options, and examples, it would be great to augment the current terraform documentation with a topology diagram, or permalinks to relevant AWS documentation, which makes it easier for someone to correlate the code to a given network architecture.

## Describe alternatives you've considered.
None

## Additional context
If there is a given convention and standard for diagrams, I would be happy to document this further myself using diagrams, however I'd need to know what tool to use (if any, unless an exported PNG would be enough). Possibly, options using diagrams as code are good enough, where the diagram generating code lives with the module repo as well.

**Comment by stv-io** [comment]
Post for activity, and a gentle nudge to @antonbabenko.

**Comment by bryantbiggs** [comment]
we are open to PRs if folks are willing to submit them for this type of information
