### ISSUE TITLE
[feature request] - Module not yet support to update routes in attachment VPCs

### ISSUE THREAD

**Issue by phu-mai** [terraform-aws-modules/terraform-aws-transit-gateway#17]
Hi guys.
Seem currently I see the modules not yet support to add routes (tgw) into VPC **Route Tables**
.....
My TF file
`
module "tgw" {
  source  = "./terraform-aws-transit-gateway"
  
  name        = "tgw"
  description = "My TGW shared with several other AWS accounts"
  
  vpc_attachments = {
    vpc = {
      vpc_id       = module.my_vpc.vpc_id
      subnet_ids   = module.my_vpc.vpc_id.private_subnets
      dns_support  = true
      transit_gateway_default_route_table_association = false
      transit_gateway_default_route_table_propagation = false
    vpc1 = {
      vpc_id       = module.my_vpc_01.vpc_id
      subnet_ids   = module.my_vpc_01.private_subnets
      dns_support  = true
    },
  }

  tags = {
    Purpose = "tgw-complete-example"
  }
}
`
Thanks so much

**Comment by sergey-korenets-fivestars** [comment]
Resolved in https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/pull/35, isn't it?
