### ISSUE TITLE
for_each value depends on resource.... error

### ISSUE THREAD

**Issue by irvintim** [terraform-aws-modules/terraform-aws-transit-gateway#2]
I am trying to use this module to manage our TGW attachments, but am getting the following error during the plan phase.  

Terraform version:
```
$ terraform -v
Terraform v0.12.20
+ provider.aws v2.47.0
```

Code:
```
module "vpc" {
  source = "git::ssh://git@gitlab.sys.XXXX.com/systems/terraform-aws-vpc.git"
  # Local copy of master branch of https://github.com/terraform-aws-modules/terraform-aws-vpc

  name = var.environment
  create_vpc = true

  cidr                 = "10.${var.network_number}.0.0/16"
  private_subnets     = ["10.${var.network_number}.0.0/24","10.${var.network_number}.1.0/24","10.${var.network_number}.2.0/24"]
  public_subnets      = ["10.${var.network_number}.10.0/24","10.${var.network_number}.11.0/24","10.${var.network_number}.12.0/24"]

  enable_nat_gateway       = "true"
  single_nat_gateway       = "false"
  enable_s3_endpoint       = "true"
  enable_dynamodb_endpoint = "false"

  enable_dns_hostnames = "true"
  enable_dns_support   = "true"

  azs = var.azs

  tags = {
    "Environment" = var.environment
  }
}

module "tgw" {
  source = "git::ssh://git@gitlab.sys.XXX.com:systems/terraform-aws-transit-gateway.git"
   # Local copy of Master branch of https://github.com/terraform-aws-modules/terraform-aws-transit-gateway

  name = "Our-tgw"
  description = "Our transit gateway to datacenters"

  vpc_attachments = {
    vpc = {
      vpc_id = module.vpc.vpc_id
      subnet_ids = module.vpc.private_subnets
      tgw_id       = data.terraform_remote_state.region_infrastructure.outputs.transit_gw_id
      dns_support = true
      ipv6_support = true

      tgw_routes = [
        "208.1.0.0/22", "207.1.0.0/22"
      ]
    }
  }

  ram_allow_external_principals = false

  tags = {
        Name        = "${var.environment} TGW"
        Environment = "${var.environment}"
  }
}
```

Errors:
```
Error: Invalid for_each argument

  on .terraform/modules/tgw/main.tf line 89, in resource "aws_ec2_transit_gateway_route_table_association" "this":
  89:   for_each = local.vpc_attachments_without_default_route_table_association

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.


Error: Invalid for_each argument

  on .terraform/modules/tgw/main.tf line 97, in resource "aws_ec2_transit_gateway_route_table_propagation" "this":
  97:   for_each = local.vpc_attachments_without_default_route_table_association

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.

Releasing state lock. This may take a few moments...
```

**Comment by rlynch-bitpusher** [comment]
@irvintim  This is a long running deficiency in TF that you can see in the following thread:
https://github.com/hashicorp/terraform/issues/4149

Given Hashicorp has know about this for half a decade (2015) and still failed to implement it - chances are slim to none that it will ever get addressed.  I recommend reading the thread in its entirety, as it sheds light on the "ideal" vs "practical" bind the authors find themselves in.

Until TF gets a wider development base with less idealist developers we are doomed to the manually iterative  `-target=module.foo` which strikes me a substandard to say the least.

**Comment by ryan-tmx** [comment]
I am currently running Terraform Enterprise and unsure how to get around this. Look a good workaround. Thanks

**Comment by ryan-tmx** [comment]
Hi @rlynch-bitpusher, so I figured out I can use the 'TF_CLI_ARGS_plan' env variable in TF Enterprise for '-target'. Last question - For this module to work what do I need to set '-target=' to? I've tried several things already and cant seem to figure it out. Your help would be much appreciated.. Thanks!

**Comment by ritzmann94** [comment]
Hi guys,

I have the same problem:

Error: Invalid for_each argument

  on .terraform/modules/tgw/terraform-aws-transit-gateway-1.1.0/main.tf line 89, in resource "aws_ec2_transit_gateway_route_table_association" "this":
  89:   for_each = local.vpc_attachments_without_default_route_table_association

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.


Error: Invalid for_each argument

  on .terraform/modules/tgw/terraform-aws-transit-gateway-1.1.0/main.tf line 97, in resource "aws_ec2_transit_gateway_route_table_propagation" "this":
  97:   for_each = local.vpc_attachments_without_default_route_table_association

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.

**Comment by jurgenweber** [comment]
could it be a bug?

https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/blob/master/main.tf#L2-L8

but the two resources are looping over the 'association' local:

https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/blob/master/main.tf#L88-L98

**Comment by jurgenweber** [comment]
maybe the first half of this has the answer we are looking for: https://discuss.hashicorp.com/t/for-each-value-depends-on-resource-attributes-that-cannot-be-determined-until-apply/6061/2

**Comment by jurgenweber** [comment]
https://github.com/hashicorp/terraform/issues/25016#issuecomment-638489617

**Comment by polymorcodeus** [comment]
A bit out of scope, but we kept running into this - one of the reasons we made a push to Terragrunt, to be able to leverage dependencies. We're using this module and end up calling the TGW module twice, the second with just the vpc_attachments, e.g.:

~~~
inputs = {
  create_tgw = false

  transit_gateway_route_table_id = dependency.tgw.outputs.this_ec2_transit_gateway_route_table_id
  
  vpc_attachments = {
    vpc0 = {
      tgw_id           = dependency.tgw.outputs.this_ec2_transit_gateway_id
      vpc_id           = dependency.vpc_servers.outputs.vpc_id
      subnet_ids    = dependency.vpc_servers.outputs.intra_subnets
...
~~~

I ended up modifying the transit_gateway_route_table_id in both aws_ec2_transit_gateway_route_table_association/propagation to avoid empty tuples error. It allows you to pass in the route table id as a variable.

~~~
transit_gateway_route_table_id = coalesce(lookup(each.value, "transit_gateway_route_table_id", null), `
    var.transit_gateway_route_table_id, var.create_tgw ? aws_ec2_transit_gateway_route_table.this[0].id : null)
~~~

**Comment by thomasfinstad** [comment]
With the change from PR #12 and using `terraform apply -target=module.tgw.aws_ec2_transit_gateway_vpc_attachment.this` before running a full `terraform apply` I was able to get an attachment through.

```
module "tgw" {
  source = "./terraform-aws-transit-gateway" # contains PR #12
  #source  = "terraform-aws-modules/transit-gateway/aws"
  #version = "1.1.0"

  name       = local.service_name
  create_tgw = false

  transit_gateway_route_table_id = local.rs_tgw.tgw["this_ec2_transit_gateway_route_table_id"]

  vpc_attachments = {
    "egress" = {
      tgw_id = local.rs_tgw.tgw["this_ec2_transit_gateway_id"]

      vpc_id = module.vpc.vpc_id

      # Assign the last 3 subnets from the vpc module
      subnet_ids   = slice(module.vpc.private_subnets, length(module.vpc.private_subnets) - 3, length(module.vpc.private_subnets))
      dns_support  = true

      tgw_routes = concat(
        local.rs_tgw.route["default"]
      )

    }
  }

  tags = module.tags.tags
}
```

**Comment by smitjainsj** [comment]
Is this issue still open as I can't find `for_each` and `depends_on` are not working together. Any resource created via `for_each` and then later its being declared in `depends_on` is not working as expected and results in cyclic dependencies error.  


Do share the experience with such approach ?

**Comment by lpaivarodrigues** [comment]
hello @smitjainsj at least for me, no ... I have tried using this TGW Module today and when running terraform plan the same issue happens. :(

**Comment by getSurreal** [comment]
I think this PR will help with some confusion https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/pull/31
