### ISSUE TITLE
Error: "transit_gateway_route_table_id": required field is not set

### ISSUE THREAD

**Issue by vsem-cinch** [terraform-aws-modules/terraform-aws-transit-gateway#24]
I get the following error even when I was uncommented the transit_gateway_route_table_id line and add my tgw route table id.

`Error: "transit_gateway_route_table_id": required field is not set
on .terraform/modules/dev_bi_dw_infra_prod_tgw/main.tf line 54, in resource "aws_ec2_transit_gateway_route" "this":
54: resource "aws_ec2_transit_gateway_route" "this" {`

Thanks

**Comment by jrab66** [comment]
@vsem-cinch do you find any solution to this issue?

**Comment by Roxyrob** [comment]
As per module code referencing using `var.transit_gateway_route_table_id` inside code using count, transit_gateway_route_table_id should be placed in module section not in vpc_attachments section.

I think this is a design issue as it is corretc to define routes in differents route tables. But if you do that you'll hit [issue #47](https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/issues/47)
