### ISSUE TITLE
RAM resource association fails (in the same account).

### ISSUE THREAD

**Issue by jihed** [terraform-aws-modules/terraform-aws-transit-gateway#28]
Hi,

module failed to create the `aws_ram_resource_association` for tgw.  I was trying to do a VPC attachement in the same account as the transit gateway. 
I
``Error: error associating RAM Resource Share: OperationNotPermittedException: The resource you are attempting to share can only be shared within your AWS Organization. This error may also occur if you have not enabled sharing with your AWS organization, or that onboarding process is still in progress.``

PS: we don't want to allow the RAM share on the AWS Org.

Thanks

**Comment by fabioformosa** [comment]
I got the same. @jihed, did you solve it?

**Comment by derekmckinnon** [comment]
@fabioformosa: Set `share_tgw = false`

**Comment by jihed** [comment]
@fabioformosa : no, we moved away from this module.
