### ISSUE TITLE
Support for TF 0.14

### ISSUE THREAD

**Issue by dlucasintouch** [terraform-aws-modules/terraform-aws-transit-gateway#29]
The aws-vpc module supports TF 0.14, but this module restricts usage to 0.12 and 0.13.  I assume there isn't anything specific in this module that would have any adverse affect based on the 0.14.x changelog.  Can this module be updated to confirm support for 0.14?

```
➜ terraform init
Initializing modules...

Error: Unsupported Terraform Core version

  on .terraform/modules/transit-gateway/versions.tf line 2, in terraform:
   2:   required_version = ">= 0.12.7, < 0.14"
```

**Comment by antonbabenko** [comment]
Fixed in #30.

[v1.4.0](https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/releases/v1.4.0) has been just released.
