### ISSUE TITLE
Cross region support using aws_ec2_transit_gateway_peering_attachment

### ISSUE THREAD

**Issue by nitrocode** [terraform-aws-modules/terraform-aws-transit-gateway#32]
We already have support for [`aws_ec2_transit_gateway_vpc_attachment`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_vpc_attachment), is this the correct module to request the addition of the [`aws_ec2_transit_gateway_peering_attachment`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_peering_attachment) resource too ?

```
module "tgw_oregon_public" {
  source  = "terraform-aws-modules/transit-gateway/aws"
  version = "~> 1.0"
  
  name        = "us-west-2_public"
  description = "us-west-2 public transit gateway"
  
  amazon_side_asn = "64512" # should be unique

  enable_auto_accept_shared_attachments = false

  vpc_attachments = {
    oregon = {
      ...
    },
  }

  # example
  peering_attachments = {
    oregon = {
      vpc_id = ""
      subnet_ids = []
    },
  }
}
```

**Comment by tfhartmann** [comment]
Hmm I'm not sure inside the module is the right place for that feature. The way i've done this so far is to add the `aws_ec2_transit_gateway_peering_attachment_accepter` and `aws_ec2_transit_gateway_peering_attachment_accepter` along side the module declarations.   I suppose you could have just the `aws_ec2_transit_gateway_peering_attachment` inside the module, and have the `aws_ec2_transit_gateway_peering_attachment_accepter` declared outside he module, but then the ordering of the creation of the different transit gateways might be challenging.  - I think you'd have a circular dependency loop. 

Anyway he's an example of what i've found works for me. 

```Hcl

module "tgw-us-east-1" {
  source                                = "terraform-aws-modules/transit-gateway/aws"
  version                               = "2.1.0"
  name                                  = "tgw-${var.env}-us-east-1"
  ...
  ...
  providers = {
    aws = aws.us-east-1
  }
}

module "tgw-us-east-2" {
  source                                = "terraform-aws-modules/transit-gateway/aws"
  version                               = "2.1.0"
  name                                  = "tgw-${var.env}-us-east-2"
  ...
  ...
  providers = {
    aws = aws.us-east-2
  }
}


resource "aws_ec2_transit_gateway_peering_attachment" "virginia-to-ohio" {
  provider                = aws.us-east-1
  peer_region             = "us-east-2"
  peer_account_id         = data.aws_caller_identity.current.account_id
  peer_transit_gateway_id = module.tgw-us-east-2.ec2_transit_gateway_id
  transit_gateway_id      = module.tgw-us-east-1.ec2_transit_gateway_id

  tags = {
    Name = "TGW Peering to us-east-2 - ${var.env}"
  }
}

resource "aws_ec2_transit_gateway_peering_attachment_accepter" "virginia-to-ohio" {
  provider                      = aws.us-east-2
  transit_gateway_attachment_id = aws_ec2_transit_gateway_peering_attachment.virginia-to-ohio.id

  tags = {
    Name = "TGW Peering to us-east-1 - ${var.env}"
  }
}
```

**Comment by tfhartmann** [comment]
@nitrocode I'm going to close this as a "wontfix" at least for now.
