### ISSUE TITLE
[feature request] - VPC Attachment Appliance mode is not supported yet in this module

### ISSUE THREAD

**Issue by gsantos1979** [terraform-aws-modules/terraform-aws-transit-gateway#33]
Please add a Appliance Mode Support of TGW VPC Attachments on this module.

"DnsSupport": "enable"|"disable",
"Ipv6Support": "enable"|"disable",
"ApplianceModeSupport": "enable"|"disable"

Reference: https://docs.aws.amazon.com/cli/latest/reference/ec2/create-transit-gateway-vpc-attachment.html

**Comment by tfhartmann** [comment]
release [v2.2.0](https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/releases/v2.2.0) should close this issue :)
