### ISSUE TITLE
Error creating EC2 tags when default route table association is false

### ISSUE THREAD

**Issue by mitchellrj** [terraform-aws-modules/terraform-aws-transit-gateway#51]
## Description

Raised as a separate issue based on comments from #23 after closing.

Errors like the following are thrown when tags are set and `enable_default_route_table_association` is `false`.

```
Error: error creating EC2 Tag (ops.company.cloud/provisioner) for resource (): error tagging resource (): InvalidParameterValue: Value ( null ) for parameter resourceId is invalid. Null/empty value for resourceId is invalid
	status code: 400, request id: 42192f9f-1546-4714-b9b2-b5b4e948ef64

  on .terraform/modules/tgw/main.tf line 44, in resource "aws_ec2_tag" "this":
  44: resource "aws_ec2_tag" "this" {
```
## Versions
 - Module: >=2.3.0 (introduced in #49)

## Reproduction
Try to configure a transit gateway with `tags` set, but `enable_default_route_table_association` is false.

## Expected behavior
EC2 tags are not set on the non-existant default route table association.

## Actual behavior
Errors like the ones @stevie- posted [here](23#issuecomment-845156109)

**Comment by michelzanini** [comment]
I am having the exact same issue. I guess the `aws_ec2_tag` resource needs to consider the value of `enable_default_route_table_association` and not try creating it when it's false.
