### ISSUE TITLE
[Feature Request] Optional Non-default Route Table

### ISSUE THREAD

**Issue by joshdinwiddie** [terraform-aws-modules/terraform-aws-transit-gateway#58]
## Is your request related to a problem? Please describe.
When I create a new TGW using this module, it creates an extra non-default TGW route table even if all my routes use the default TGW route table.  

## Describe the solution you'd like.
Non-default route table = false

## Describe alternatives you've considered.
Right now, I am just manually deleting the extra table every time I run the Terraform since it's blank.  It's not a huge deal, I just think it would be a nice feature - that is unless I'm doing something wrong?  Code below:

```
module "tgw" {
  source = "terraform-aws-modules/transit-gateway/aws"
  name   = "TGW-Name"

  enable_auto_accept_shared_attachments = true
  
  vpc_attachments = {
    vpc = {
      vpc_id       = data.aws_vpc.vpc.id                                 
      subnet_ids   = var.subnets
      dns_support  = true
      ipv6_support = false
    }
  } 

  ram_allow_external_principals = true
  ram_principals                = ["##########"]
  
  tags = {
    Ticket = "######"
  }

  tgw_route_table_tags = {
    Name = "Non-default Route Table"
  }
}
```

**Comment by coofercat** [comment]
It seems that if you set the following when calling this module, the additional route table is not created:

`enable_default_route_table_association = false`
`enable_default_route_table_propagation = false`

In my case I'm then bumping into other problems, but don't have the additional (non-default) route table any longer. I won't comment on the logical difficulties with these settings and their outcome ;-)
