### ISSUE TITLE
VPC routes are not added, causing traffic not to flow through TGW

### ISSUE THREAD

**Issue by jacobm3** [terraform-aws-modules/terraform-aws-transit-gateway#78]
## Description

This might be operator error, but I can't get the module to add routes for the TGW in each VPC, which causes VPCs not to route to each other through the TGW.

Is the TGW module intended to do this? If not, could the examples include code showing how to add the routes in Terraform, using TGW and VPC module outputs?

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
```
$ terraform modules -version
Terraform v1.2.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.22.0
```

- Terraform version:

```
$ terraform version
Terraform v1.2.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.22.0
```

- Provider version(s):

```
$ terraform providers -version
Terraform v1.2.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.22.0
```

## Reproduction Code [Required]

```
locals {
  region = "us-east-1"
  name   = "wolf-test"
}

provider "aws" {
  region = local.region
}

module "tgw" {
  source    = "terraform-aws-modules/transit-gateway/aws"
  version   = "~> 2.0"
  name      = "${local.name}-tgw"
  share_tgw = false

  vpc_attachments = {
    vpc1 = {
      vpc_id       = module.vpc1.vpc_id
      subnet_ids   = module.vpc1.public_subnets
      dns_support  = true
      ipv6_support = false
      tgw_routes = [{ destination_cidr_block = "10.20.0.0/16" }]
    },
    vpc2 = {
      vpc_id       = module.vpc2.vpc_id
      subnet_ids   = module.vpc2.public_subnets
      dns_support  = true
      ipv6_support = false
      tgw_routes = [{ destination_cidr_block = "10.21.0.0/16" }]
    }
  }
}

module "vpc1" {
  source         = "terraform-aws-modules/vpc/aws"
  version        = "~> 3.0"
  name           = "${local.name}-vpc1"
  cidr           = "10.20.0.0/16"
  azs            = ["${local.region}a", "${local.region}b", "${local.region}c"]
  public_subnets = ["10.20.1.0/24", "10.20.2.0/24", "10.20.3.0/24"]
  enable_ipv6    = false
}

module "vpc2" {
  source         = "terraform-aws-modules/vpc/aws"
  version        = "~> 3.0"
  name           = "${local.name}-vpc2"
  cidr           = "10.21.0.0/16"
  azs            = ["${local.region}a", "${local.region}b", "${local.region}c"]
  public_subnets = ["10.21.1.0/24", "10.21.2.0/24", "10.21.3.0/24"]
  enable_ipv6    = false
}
```

I've tried various combinations of VPC attachment tgw_routes lists, transit_gateway_default_route_table_association, and transit_gateway_default_route_table_propagation but the module never adds the VPC routes required for instances to connect to each other through the TGW.

```
terraform init
terraform apply
```

Are you using workspaces? 
No

Have you cleared the local cache (see Notice section above)?
Yes

## Expected behavior

I expected a TGW module to add routes to the VPCs which are required for routing to work. If the TGW module isn't intended to do that, it would be helpful for the included examples to show Terraform code to add the routes using the TGW and VPC module outputs.

## Actual behavior

VPC routes aren't added by the TGW module. Hosts on each VPC can't reach each other until I manually add the VPC routes.

**Comment by derekmckinnon** [comment]
This module creates 2 TGW route tables, one of which is the default association route table and one of which is just another route table. When you use the `tgw_routes`, this module seems to populate those routes to the second table where none of the VPC attachments are associated. I would classify that as a bug or at the very least extremely misleading functionality.

However, I think the main reason why traffic is not flowing is because you are missing route table entries in both VPCs that specify each other's CIDR blocks and the TGW ID.

Example (untested with your configuration):

```hcl
resource "aws_route" "vpc1_to_vpc2" {
  for_each = module.vpc1.public_route_table_ids

  route_table_id         = each.key
  destination_cidr_block = "10.21.0.0/16"
  transit_gateway_id     = module.tgw.ec2_transit_gateway_id
}

resource "aws_route" "vpc2_to_vpc1" {
  for_each = module.vpc2.public_route_table_ids

  route_table_id         = each.key
  destination_cidr_block = "10.20.0.0/16"
  transit_gateway_id     = module.tgw.ec2_transit_gateway_id
}
```

**Comment by msharma24** [comment]
@jacobm3  I just add the route using a resource 
https://github.com/msharma24/terraform-aws-network-firewall-deployment-models/blob/main/centralized/spoke-vpc-a.tf#L48

**Comment by mwthink** [comment]
+1 for this behavior to be treated like a bug. Either the module should put routes on that route_table it explicitly creates or it should use the default RTB for all routes. 

With the current state of the module (`2.8.0`) I am going to create my routes outside of the module (just using the module for creation of the TGW + attachments). Even with this setup though, it creates this 2nd route table which goes un-used and there is no way to disable it.

**Comment by v-rosa** [comment]
this is still revelant

**Comment by v-rosa** [comment]
@jacobm3, can you try this setup? I've make it to work with a similiar approach.

```hcl
module "tgw" {
  source    = "terraform-aws-modules/transit-gateway/aws"
  version   = "~> 2.0"
  name      = "${local.name}-tgw"
  share_tgw = false

  vpc_attachments = {
    vpc1 = {
      vpc_id       = module.vpc1.vpc_id
      subnet_ids   = module.vpc1.public_subnets
      dns_support  = true
      ipv6_support = false

      vpc_route_table_ids  = concat([module.vpc1.vpc_main_route_table_id], module.vpc1.public_route_table_ids, module.vpc1.private_route_table_ids)
      tgw_destination_cidr = module.vpc2.vpc_cidr_block

      transit_gateway_default_route_table_association = true
      transit_gateway_default_route_table_propagation = true
      
      tgw_routes = [{ destination_cidr_block = module.vpc2.vpc_cidr_block }]
    },
    
    vpc2 = {
      vpc_id       = module.vpc2.vpc_id
      subnet_ids   = module.vpc2.public_subnets
      dns_support  = true
      ipv6_support = false

      vpc_route_table_ids  = concat([module.vpc2.vpc_main_route_table_id], module.vpc2.public_route_table_ids, module.vpc2.private_route_table_ids)
      tgw_destination_cidr = module.vpc1.vpc_cidr_block

      transit_gateway_default_route_table_association = true
      transit_gateway_default_route_table_propagation = true
      
      tgw_routes = [{ destination_cidr_block = module.vpc1.vpc_cidr_block }]
    }
  }
}
```

**Comment by britthouser** [comment]
I'm also hitting the problem where tgw_routes I inject at the attachment time are not put into the correct routing table.  In our case, we have a central egress VPC, and I want to inject the default route into the TGW when I attach to that VPC.

```
 vpc_attachments = {
    vpc = {
      vpc_id       = module.aws_vpc.vpc_id
      subnet_ids   = module.aws_vpc.private_subnets
      dns_support  = var.tgw_vpc_dns_support
      ipv6_support = var.tgw_vpc_ipv6_support
      tgw_routes = [
        {
          destination_cidr_block = "0.0.0.0/0"
        }
      ]
    }
  }
```

However this default route gets put into the wrong table.
