### ISSUE TITLE
Please provide (add) additional example

### ISSUE THREAD

**Issue by sahaqaa** [terraform-aws-modules/terraform-aws-transit-gateway#84]
Hello, i'm relatively new to Terraform and usage of Terraform modules such as "terraform-aws-transit-gateway" and "terraform-aws-vpc".
I would like to ask you to provide (add) additional example :-)
In my case i have multiple AWS Accounts, but to make it simpler I have:
-	account A (production account, created long time ago, fully manual)
-	account B (newly added account)
In account A in us-west-1 we have TGW which shared with multiple AWS Accounts. In account A in us-west-1 I went ahead created manually RAM resource share for TGW. In Account B I accepted shared resource (TGW).
I wanted to research "terraform-aws-vpc" module to create VPCs / Subnets / NATGW / IGW etc. And then I found out that "terraform-aws-transit-gateway" module can also manage TGW and Transit gateway attachments and Transit gateway route tables.
I would like to try to manage Transit gateway attachment and Transit gateway route table in Account B via "terraform-aws-transit-gateway" module.
In examples (https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/tree/master/examples) I see two options, but I was not able to understand how to use "terraform-aws-transit-gateway" module for my use case.

Could you please create additional example?
Thank you.

**Comment by sahaqaa** [comment]
^^ Still actual

**Comment by antonbabenko** [comment]
I am sure it is an issue, but I don't know when we will be able to find time to handle this module realistically. Unfortunately.

**Comment by sahaqaa** [comment]
I understand. It's not urgent or critical. May i ask you to put it somewhere in backlog? :-)
Because with label "stale" this Issue will be closed and gone for good and therefore won't be done at all.
